Imports System.Data.Linq
Imports DevExpress.XtraEditors.Controls
Imports DevExpress.XtraEditors.Repository
Imports DevExpress.XtraGrid.Columns
Imports DevExpress.XtraGrid.Views.Grid

Public Class XtraUCParametr
    Dim db As New DataClassesDorogaDataContext
    Dim riMemoEdit As New RepositoryItemMemoEdit()
    Dim riLookUpEditTable As New RepositoryItemLookUpEdit()

    Public Sub New()
        InitializeComponent()

        Me.GridControlSettings.RepositoryItems.Add(riLookUpEditTable)
        Me.GridControlSettings.RepositoryItems.Add(riMemoEdit)

        Call InitRILookUpEdit()
    End Sub

    Private Sub XtraUCParametr_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        If (Not DBConnect()) Then Return
    End Sub

#Region "Пользовательскте процедуры и функции"
    Private Function DBConnect() As Boolean
        db = New DataClassesDorogaDataContext()
        ' This line of code is generated by Data Source Configuration Wizard
        'контролерBindingSource.DataSource = New iTPDoroga.DataClassesDorogaDataContext().Контролер

        Dim tbControler = From qTb In db.GetTable(Of Контролер)()

        Call GVSettings(Me.GridViewMain)
        Me.контролерBindingSource.DataSource = tbControler
        Return True
    End Function

    Private Sub GVSettings(ByVal view As GridView)
        view.BestFitColumns()
        view.OptionsView.ColumnAutoWidth = True
        view.Columns("Таблица").ColumnEdit = riLookUpEditTable

        Call riLookUpEditData(0)

        view.Columns("Индекс_контролера").Caption = "Индекс контролера"
        view.Columns("Имя_контролера").Caption = "Имя контролера"
        view.Columns("Дата_записи").Caption = "Дата записи"
        view.Columns("Дата_записи").AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center
        view.Columns("Дата_исправления").Caption = "Дата исправления"
        view.Columns("Дата_исправления").AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center
        riMemoEdit.WordWrap = True
        view.Columns("Примечание").ColumnEdit = riMemoEdit
        view.Columns("кодКонтролер").Visible = False

        For Each column As GridColumn In view.Columns
            column.AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center
        Next

        view.OptionsView.RowAutoHeight = True
    End Sub

    Private Sub riLookUpEditData(ByVal i As Integer)
        ' Получение списка таблиц
        db = New DataClassesDorogaDataContext()

        Dim _List0 As IEnumerable(Of ListOfTablesResult) = db.ListOfTables().ToList()

        riLookUpEditTable.DataSource = Nothing
        riLookUpEditTable.DataSource = _List0
    End Sub

    Private Sub InitRILookUpEdit()
        Dim coll As LookUpColumnInfoCollection = riLookUpEditTable.Columns

        coll.Add(New LookUpColumnInfo("row", 0))
        coll.Add(New LookUpColumnInfo("name", 0))
        Me.riLookUpEditTable.AppearanceDropDownHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center
        Me.riLookUpEditTable.BestFitMode = BestFitMode.BestFitResizePopup
        Me.riLookUpEditTable.SearchMode = SearchMode.AutoComplete
        Me.riLookUpEditTable.AutoSearchColumnIndex = 1
        Me.riLookUpEditTable.ValueMember = "name"
        Me.riLookUpEditTable.DisplayMember = "name"
        Me.riLookUpEditTable.Columns("row").Caption = "Номер в списке"
        Me.riLookUpEditTable.Columns("name").Caption = "Таблица в БД"
    End Sub
#End Region
End Class
