Imports DevExpress.XtraGrid.Columns
Imports DevExpress.XtraGrid.Views.Grid

Public Class XtraUCParametr
    Dim db As New DataClassesDorogaDataContext

    Public Sub New()
        InitializeComponent()

        ' This line of code is generated by Data Source Configuration Wizard
        контролерBindingSource.DataSource = New iTPDoroga.DataClassesDorogaDataContext().Контролер
    End Sub
End Class
