<?xml version="1.0" encoding="utf-8"?><Database Name="Doroga" Class="DataClassesDorogaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WIN2012R2HOME\ASUSQLH;Initial Catalog=Doroga;Persist Security Info=True;User ID=ReshelieMain" SettingsObjectName="iTPDoroga.Settings" SettingsPropertyName="DorogaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.address" Member="address">
    <Type Name="address">
      <Column Name="counter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="OCATD" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Building" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Corpus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Construction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ALTNAMES" Member="ALTNAMES">
    <Type Name="ALTNAMES">
      <Column Name="OLDCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NEWCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[LEVEL]" Member="LEVEL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOMA" Member="DOMA">
    <Type Name="DOMA">
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KORP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOCR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[INDEX]" Member="INDEX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GNINMB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OCATD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FLAT" Member="FLAT">
    <Type Name="FLAT">
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GNINMB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[INDEX]" Member="INDEX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KLADR" Member="KLADR">
    <Type Name="KLADR">
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOCR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[INDEX]" Member="INDEX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GNINMB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OCATD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SOCRBASE" Member="SOCRBASE">
    <Type Name="SOCRBASE">
      <Column Name="[LEVEL]" Member="LEVEL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SCNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOCRNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KOD_T_ST" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.STREET" Member="STREET">
    <Type Name="STREET">
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOCR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[INDEX]" Member="INDEX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GNINMB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OCATD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Город" Member="Город">
    <Type Name="Город">
      <Column Name="кодГород" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Название" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Краткое" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="кодСтрана" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Область" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Край" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Страна_Город" Member="Страна" ThisKey="кодСтрана" OtherKey="кодСтрана" Type="Страна" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Должность" Member="Должность">
    <Type Name="Должность">
      <Column Name="кодДолжность" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Аббревиатура" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Должность_Сотрудник" Member="Сотрудник" ThisKey="кодДолжность" OtherKey="кодДолжность" Type="Сотрудник" />
    </Type>
  </Table>
  <Table Name="dbo.Кафедра" Member="Кафедра">
    <Type Name="Кафедра">
      <Column Name="КодКафедра" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="шифрКафедра" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Аббревиатура" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодУчреждение" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Кафедра_Кафедра_Сотрудник" Member="Кафедра_Сотрудник" ThisKey="КодКафедра" OtherKey="кодКафедра" Type="Кафедра_Сотрудник" />
      <Association Name="Факультет_Кафедра" Member="Факультет" ThisKey="кодФакультет" OtherKey="кодФакультет" Type="Факультет" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Кафедра_Сотрудник" Member="Кафедра_Сотрудник">
    <Type Name="Кафедра_Сотрудник">
      <Column Name="кодКафедра" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Кафедра_Кафедра_Сотрудник" Member="Кафедра" ThisKey="кодКафедра" OtherKey="КодКафедра" Type="Кафедра" IsForeignKey="true" />
      <Association Name="Сотрудник_Кафедра_Сотрудник" Member="Сотрудник" ThisKey="кодСотрудник" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Паспорт" Member="Паспорт">
    <Type Name="Паспорт">
      <Column Name="кодПаспорт" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Серия" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Номер" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="[Код подразделения]" Member="Код_подразделения" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="Когда" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Кем" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Паспорт" Member="Сотрудник" ThisKey="кодСотрудник" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Степень" Member="Степень">
    <Type Name="Степень">
      <Column Name="кодСтепень" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Аббревиатура" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Степень_Сотрудник" Member="Сотрудник" ThisKey="кодСтепень" OtherKey="кодСтепень" Type="Сотрудник" />
    </Type>
  </Table>
  <Table Name="dbo.Страна" Member="Страна">
    <Type Name="Страна">
      <Column Name="кодСтрана" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[На английском]" Member="На_английском" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Полное" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Alpha2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Alpha3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ISO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Часть света]" Member="Часть_света" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Расположение" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Флаг" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Флаг 1]" Member="Флаг_1" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Флаг 2]" Member="Флаг_2" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Страна_Город" Member="Город" ThisKey="кодСтрана" OtherKey="кодСтрана" Type="Город" />
    </Type>
  </Table>
  <Table Name="dbo.Факультет" Member="Факультет">
    <Type Name="Факультет">
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="шифрФакультет" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Наименование_Факультет" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Аббр_Факультет" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Факультет_Кафедра" Member="Кафедра" ThisKey="кодФакультет" OtherKey="кодФакультет" Type="Кафедра" />
      <Association Name="Факультет_Сотрудник" Member="Сотрудник" ThisKey="кодФакультет" OtherKey="кодФакультет" Type="Сотрудник" />
    </Type>
  </Table>
  <Table Name="dbo.Параметр" Member="Параметр">
    <Type Name="Параметр">
      <Column Name="кодПараметра" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="кодКонтролер" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Дата записи]" Member="Дата_записи" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Дата исправления]" Member="Дата_исправления" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Контролер_Параметр" Member="Контролер" ThisKey="кодКонтролер" OtherKey="кодКонтролер" Type="Контролер" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Контролер" Member="Контролер">
    <Type Name="Контролер">
      <Column Name="кодКонтролер" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Таблица" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Поле" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Дата записи]" Member="Дата_записи" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Дата исправления]" Member="Дата_исправления" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Контролер_Параметр" Member="Параметр" ThisKey="кодКонтролер" OtherKey="кодКонтролер" Type="Параметр" />
    </Type>
  </Table>
  <Table Name="dbo.Email" Member="Email">
    <Type Name="Email">
      <Column Name="кодEmail" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип email]" Member="Тип_email" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Email" Member="Сотрудник" ThisKey="кодСотрудник" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Адрес" Member="Адрес">
    <Type Name="Адрес">
      <Column Name="кодАдрес" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="типАдрес" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Почтовый индекс]" Member="Почтовый_индекс" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="[Субъект РФ (регион)]" Member="Субъект_РФ__регион_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование района]" Member="Наименование_района" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование города]" Member="Наименование_города" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование населенного пункта]" Member="Наименование_населенного_пункта" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование улицы]" Member="Наименование_улицы" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="[Номер дома (владение)]" Member="Номер_дома__владение_" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Корпус (строение)]" Member="Корпус__строение_" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="[Квартира (офис)]" Member="Квартира__офис_" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Адрес" Member="Сотрудник" ThisKey="кодСотрудник" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Пароль" Member="Пароль">
    <Type Name="Пароль">
      <Column Name="IDPassport" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Passport1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Passport2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDAuthor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Дата записи]" Member="Дата_записи" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Дата исправления]" Member="Дата_исправления" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Пароль" Member="Сотрудник" ThisKey="IDUser" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Контакт" Member="Контакт">
    <Type Name="Контакт">
      <Column Name="кодКонтакт" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип Контакт]" Member="Тип_Контакт" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Контакт" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Контакт" Member="Сотрудник" ThisKey="кодСотрудник" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Сотрудник" Member="Сотрудник">
    <Type Name="Сотрудник">
      <Column Name="КодСотрудник" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="кодПол" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Дата Рождения]" Member="Дата_Рождения" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="[Место Рождения]" Member="Место_Рождения" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="кодГражданство" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КодСемейноеПоложение" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодСтепень" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодДолжность" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Кафедра_Сотрудник" Member="Кафедра_Сотрудник" ThisKey="КодСотрудник" OtherKey="кодСотрудник" Type="Кафедра_Сотрудник" />
      <Association Name="Сотрудник_Паспорт" Member="Паспорт" ThisKey="КодСотрудник" OtherKey="кодСотрудник" Type="Паспорт" />
      <Association Name="Сотрудник_Email" Member="Email" ThisKey="КодСотрудник" OtherKey="кодСотрудник" Type="Email" />
      <Association Name="Сотрудник_Адрес" Member="Адрес" ThisKey="КодСотрудник" OtherKey="кодСотрудник" Type="Адрес" />
      <Association Name="Сотрудник_Пароль" Member="Пароль" ThisKey="КодСотрудник" OtherKey="IDUser" Type="Пароль" />
      <Association Name="Сотрудник_Контакт" Member="Контакт" ThisKey="КодСотрудник" OtherKey="кодСотрудник" Type="Контакт" />
      <Association Name="Сотрудник_Фото" Member="Фото" ThisKey="КодСотрудник" OtherKey="кодСотрудник" Type="Фото" />
      <Association Name="Должность_Сотрудник" Member="Должность" ThisKey="кодДолжность" OtherKey="кодДолжность" Type="Должность" IsForeignKey="true" />
      <Association Name="Степень_Сотрудник" Member="Степень" ThisKey="кодСтепень" OtherKey="кодСтепень" Type="Степень" IsForeignKey="true" />
      <Association Name="Факультет_Сотрудник" Member="Факультет" ThisKey="кодФакультет" OtherKey="кодФакультет" Type="Факультет" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Фото" Member="Фото">
    <Type Name="Фото">
      <Column Name="кодФото" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип фото]" Member="Тип_фото" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Источник" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Хранилище" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="База" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Оригинал" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Сотрудник_Фото" Member="Сотрудник" ThisKey="кодСотрудник" OtherKey="КодСотрудник" Type="Сотрудник" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.CountСписок_сотрудников" Method="CountСписок_сотрудников" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ListOfTables" Method="ListOfTables" IsComposable="true">
    <ElementType Name="ListOfTablesResult">
      <Column Name="row" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetListFieldTable" Method="GetListFieldTable" IsComposable="true">
    <Parameter Name="TableName" Parameter="tableName" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="GetListFieldTableResult">
      <Column Name="row" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IS_NULLABLE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="COLUMN_DEFAULT" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParameters" Method="GetParameters" IsComposable="true">
    <Parameter Name="кодКонтролер" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParametersResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_DeleteКонтакт" Method="p_DeleteКонтакт">
    <Parameter Name="кодКонтакт" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.p_DeleteСотрудник" Method="p_DeleteСотрудник">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.p_DeleteФакультет" Method="p_DeleteФакультет">
    <Parameter Name="кодФакультет" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.p_GetКафедра" Method="p_GetКафедра">
    <Parameter Name="КодКафедра" Parameter="кодКафедра" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКафедраResult">
      <Column Name="КодКафедра" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="шифрКафедра" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Наименование" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Аббревиатура" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодУчреждение" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКафедра_Сотрудник" Method="p_GetКафедра_Сотрудник">
    <Parameter Name="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКафедра_СотрудникResult">
      <Column Name="кодКафедра" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКонтакт" Method="p_GetКонтакт">
    <Parameter Name="кодКонтакт" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКонтактResult">
      <Column Name="кодКонтакт" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип Контакт]" Member="Тип_Контакт" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Контакт" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetСотрудник" Method="p_GetСотрудник">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetСотрудникResult">
      <Column Name="КодСотрудник" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="кодПол" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Дата Рождения]" Member="Дата_Рождения" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="[Место Рождения]" Member="Место_Рождения" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="кодГражданство" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КодСемейноеПоложение" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодСтепень" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодДолжность" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetФакультет" Method="p_GetФакультет">
    <Parameter Name="кодФакультет" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetФакультетResult">
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="шифрФакультет" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Наименование_Факультет" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Аббр_Факультет" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_SaveКафедра" Method="p_SaveКафедра">
    <Parameter Name="КодКафедра" Parameter="кодКафедра" Type="System.Int32" DbType="Int" />
    <Parameter Name="шифрКафедра" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Наименование" Parameter="наименование" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Аббревиатура" Parameter="аббревиатура" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="кодФакультет" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодУчреждение" Type="System.Int32" DbType="Int" />
    <Parameter Name="Записал" Parameter="записал" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Исправил" Parameter="исправил" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Примечание" Parameter="примечание" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="p_SaveКафедраResult">
      <Column Name="NewRecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_SaveКафедра_Сотрудник" Method="p_SaveКафедра_Сотрудник">
    <Parameter Name="кодКафедра" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодСотрудник" Type="System.Int32" DbType="Int" />
    <Parameter Name="Записал" Parameter="записал" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Исправил" Parameter="исправил" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Примечание" Parameter="примечание" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="p_SaveКафедра_СотрудникResult">
      <Column Name="NewRecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_SaveКонтакт" Method="p_SaveКонтакт">
    <Parameter Name="кодКонтакт" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодСотрудник" Type="System.Int32" DbType="Int" />
    <Parameter Name="Тип_Контакт" Parameter="тип_Контакт" Type="System.Int32" DbType="Int" />
    <Parameter Name="Контакт" Parameter="контакт" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Записал" Parameter="записал" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Исправил" Parameter="исправил" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Примечание" Parameter="примечание" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="p_SaveКонтактResult">
      <Column Name="NewRecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_SaveСотрудник" Method="p_SaveСотрудник">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <Parameter Name="Фамилия" Parameter="фамилия" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Имя" Parameter="имя" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Отчество" Parameter="отчество" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="кодПол" Type="System.Int32" DbType="Int" />
    <Parameter Name="Дата_Рождения" Parameter="дата_Рождения" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Место_Рождения" Parameter="место_Рождения" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="кодГражданство" Type="System.Int32" DbType="Int" />
    <Parameter Name="КодСемейноеПоложение" Parameter="кодСемейноеПоложение" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодСтепень" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодДолжность" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодФакультет" Type="System.Int32" DbType="Int" />
    <Parameter Name="Записал" Parameter="записал" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Исправил" Parameter="исправил" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Примечание" Parameter="примечание" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="p_SaveСотрудникResult">
      <Column Name="NewRecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_SaveФакультет" Method="p_SaveФакультет">
    <Parameter Name="кодФакультет" Type="System.Int32" DbType="Int" />
    <Parameter Name="шифрФакультет" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Наименование_Факультет" Parameter="наименование_Факультет" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Аббр_Факультет" Parameter="аббр_Факультет" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Записал" Parameter="записал" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Исправил" Parameter="исправил" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Примечание" Parameter="примечание" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="p_SaveФакультетResult">
      <Column Name="NewRecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfFullДолжность" Method="p_GetListOfFullДолжность" IsComposable="true">
    <ElementType Name="p_GetListOfFullДолжностьResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(153)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfFullКафедра" Method="p_GetListOfFullКафедра" IsComposable="true">
    <ElementType Name="p_GetListOfFullКафедраResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(268)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfFullКафедраАббр" Method="p_GetListOfFullКафедраАббр" IsComposable="true">
    <ElementType Name="p_GetListOfFullКафедраАббрResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfFullСотрудник" Method="p_GetListOfFullСотрудник" IsComposable="true">
    <ElementType Name="p_GetListOfFullСотрудникResult">
      <Column Name="КодСотрудник" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="кодПол" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Дата Рождения]" Member="Дата_Рождения" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="[Место Рождения]" Member="Место_Рождения" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="кодГражданство" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="КодСемейноеПоложение" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодСтепень" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодДолжность" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="кодФакультет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfFullСтепень" Method="p_GetListOfFullСтепень" IsComposable="true">
    <ElementType Name="p_GetListOfFullСтепеньResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(113)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfFullФакультет" Method="p_GetListOfFullФакультет" IsComposable="true">
    <ElementType Name="p_GetListOfFullФакультетResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(153)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfДолжность" Method="p_GetListOfДолжность" IsComposable="true">
    <ElementType Name="p_GetListOfДолжностьResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfСтепень" Method="p_GetListOfСтепень" IsComposable="true">
    <ElementType Name="p_GetListOfСтепеньResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetListOfФакультет" Method="p_GetListOfФакультет" IsComposable="true">
    <ElementType Name="p_GetListOfФакультетResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКафедраФакультет" Method="p_GetКафедраФакультет" IsComposable="true">
    <Parameter Name="КодФакультет" Parameter="кодФакультет" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКафедраФакультетResult">
      <Column Name="row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(268)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКонтактСотрудник" Method="p_GetКонтактСотрудник" IsComposable="true">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКонтактСотрудникResult">
      <Column Name="кодКонтакт" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип Контакт]" Member="Тип_Контакт" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Контакт" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetEmailСотрудник" Method="p_GetEmailСотрудник" IsComposable="true">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetEmailСотрудникResult">
      <Column Name="кодEmail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип email]" Member="Тип_email" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКонтактАдрес" Method="p_GetКонтактАдрес" IsComposable="true">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКонтактАдресResult">
      <Column Name="кодАдрес" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="типАдрес" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Почтовый индекс]" Member="Почтовый_индекс" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="[Субъект РФ (регион)]" Member="Субъект_РФ__регион_" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование района]" Member="Наименование_района" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование города]" Member="Наименование_города" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование населенного пункта]" Member="Наименование_населенного_пункта" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Наименование улицы]" Member="Наименование_улицы" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="[Номер дома (владение)]" Member="Номер_дома__владение_" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="[Корпус (строение)]" Member="Корпус__строение_" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="[Квартира (офис)]" Member="Квартира__офис_" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКонтактПаспорт" Method="p_GetКонтактПаспорт" IsComposable="true">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКонтактПаспортResult">
      <Column Name="кодПаспорт" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Серия" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Номер" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="[Код подразделения]" Member="Код_подразделения" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="Когда" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Кем" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКонтактПароль" Method="p_GetКонтактПароль" IsComposable="true">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКонтактПарольResult">
      <Column Name="IDPassport" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Passport1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Passport2" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDAuthor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Дата записи]" Member="Дата_записи" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Дата исправления]" Member="Дата_исправления" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_GetКонтактФото" Method="p_GetКонтактФото" IsComposable="true">
    <Parameter Name="КодСотрудник" Parameter="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetКонтактФотоResult">
      <Column Name="кодФото" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип фото]" Member="Тип_фото" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Источник" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Хранилище" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="База" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Оригинал" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CountФото_сотрудников" Method="CountФото_сотрудников" IsComposable="true">
    <Parameter Name="кодСотрудник" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.p_GetDBInfo" Method="p_GetDBInfo" IsComposable="true">
    <ElementType Name="p_GetDBInfoResult">
      <Column Name="SERVER" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DB_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FILE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Drive" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="Physical_Name" Type="System.String" DbType="NVarChar(260) NOT NULL" CanBeNull="false" />
      <Column Name="Ext" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="SIZE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Growth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckCreateDirectory" Method="CheckCreateDirectory">
    <Parameter Name="checkdir" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="CheckCreateDirectoryResult">
      <Column Name="[Результат: ]" Member="Результат__" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_SaveФото" Method="p_SaveФото">
    <Parameter Name="кодФото" Type="System.Int32" DbType="Int" />
    <Parameter Name="кодСотрудник" Type="System.Int32" DbType="Int" />
    <Parameter Name="Тип_фото" Parameter="тип_фото" Type="System.Int32" DbType="Int" />
    <Parameter Name="Источник" Parameter="источник" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Хранилище" Parameter="хранилище" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="База" Parameter="база" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Оригинал" Parameter="оригинал" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="Записал" Parameter="записал" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Исправил" Parameter="исправил" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="Примечание" Parameter="примечание" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="p_SaveФотоResult">
      <Column Name="NewRecordID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.p_DeleteФото" Method="p_DeleteФото">
    <Parameter Name="кодФото" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.p_GetФото_Сотрудник" Method="p_GetФото_Сотрудник">
    <Parameter Name="кодСотрудник" Type="System.Int32" DbType="Int" />
    <ElementType Name="p_GetФото_СотрудникResult">
      <Column Name="кодФото" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="кодСотрудник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Тип фото]" Member="Тип_фото" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Источник" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Хранилище" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="База" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Оригинал" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
      <Column Name="Записал" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаЗаписал" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Исправил" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="датаИсправил" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>